// DO NOT EDIT: Code generated by matcha from footer.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree(placeholder placeholder: String) -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "<footer>
  <small>Built with Dream + HTMX + Pico CSS</small>
</footer>

")

    tree
}

pub fn render(placeholder placeholder: String) -> String {
    string_tree.to_string(render_tree(placeholder: placeholder))
}

