name: Check Hex Version
description: Check if a module version already exists on Hex

inputs:
  module_dir:
    description: Path to the module directory (e.g., modules/config)
    required: true
  force_publish:
    description: Force publish even if version exists
    required: false
    default: 'false'

outputs:
  should_publish:
    description: Whether the module should be published
    value: ${{ steps.check.outputs.should_publish }}
  version:
    description: The current version
    value: ${{ steps.check.outputs.version }}
  package_name:
    description: The package name
    value: ${{ steps.check.outputs.package_name }}

runs:
  using: composite
  steps:
    - name: Check if version exists on Hex
      id: check
      shell: bash
      env:
        FORCE_PUBLISH: ${{ inputs.force_publish }}
      run: |
        MODULE_DIR="${{ inputs.module_dir }}"
        GLEAM_TOML="$MODULE_DIR/gleam.toml"

        if [ ! -f "$GLEAM_TOML" ]; then
          echo "Error: $GLEAM_TOML not found"
          exit 1
        fi

        # Check if force publish is enabled
        if [ "$FORCE_PUBLISH" = "true" ]; then
          echo "FORCE_PUBLISH is enabled, bypassing version check"
          CURRENT_VERSION=$(grep '^version = ' "$GLEAM_TOML" | sed 's/version = "\(.*\)"/\1/')
          PACKAGE_NAME=$(grep '^name = ' "$GLEAM_TOML" | sed 's/name = "\(.*\)"/\1/')
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get current version and package name
        CURRENT_VERSION=$(grep '^version = ' "$GLEAM_TOML" | sed 's/version = "\(.*\)"/\1/')
        PACKAGE_NAME=$(grep '^name = ' "$GLEAM_TOML" | sed 's/name = "\(.*\)"/\1/')

        if [ -z "$CURRENT_VERSION" ]; then
          echo "Error: Could not extract version from $GLEAM_TOML"
          exit 1
        fi

        if [ -z "$PACKAGE_NAME" ]; then
          echo "Error: Could not extract package name from $GLEAM_TOML"
          exit 1
        fi

        echo "Checking if $PACKAGE_NAME version $CURRENT_VERSION exists on Hex..."

        # Check if version exists on Hex
        HEX_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://hex.pm/api/packages/$PACKAGE_NAME/releases/$CURRENT_VERSION")

        if [ "$HEX_RESPONSE" = "200" ]; then
          echo "Version $CURRENT_VERSION already exists on Hex, skipping publish"
          echo "should_publish=false" >> $GITHUB_OUTPUT
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        elif [ "$HEX_RESPONSE" = "404" ]; then
          echo "Version $CURRENT_VERSION does not exist on Hex, will publish"
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        else
          echo "Warning: Unexpected response from Hex API (HTTP $HEX_RESPONSE), will attempt to publish"
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        fi

